### ISSUE TITLE
Building fails because of fcrepo version

### ISSUE THREAD

**Issue by DonRichards** [Islandora-CLAW/CLAW#1022]
Running on OSX with no modifications. 
ansible 2.7.6
Vagrant 2.2.3

```terminal
$ vagrant up
......
.....
.....
TASK [Islandora-Devops.tomcat8 : start tomcat] *********************************
Wednesday 06 February 2019  13:55:53 -0500 (0:00:00.560)       0:13:01.116 ****
ok: [default]

TASK [Islandora-Devops.fcrepo : Download fcrepo war] ***************************
Wednesday 06 February 2019  13:55:54 -0500 (0:00:00.332)       0:13:01.448 ****
fatal: [default]: FAILED! => {"changed": false, "dest": "/var/lib/tomcat8/webapps/fcrepo.war", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://github.com/fcrepo4-exts/fcrepo-webapp-plus/releases/download/fcrepo-webapp-plus-5.0.0/fcrepo-webapp-plus-5.0.0.war"}

RUNNING HANDLER [Islandora-Devops.tomcat8 : tomcat8 restart tomcat8] ***********
Wednesday 06 February 2019  13:55:54 -0500 (0:00:00.728)       0:13:02.177 ****
	to retry, use: --limit @/Users/support/Desktop/github/claw-playbook/playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=241  changed=105  unreachable=0    failed=1

Wednesday 06 February 2019  13:55:54 -0500 (0:00:00.003)       0:13:02.181 ****
===============================================================================
geerlingguy.drupal : Install dependencies with composer require (this may take a while). - 232.69s
geerlingguy.drupal : Generate Drupal project with composer package in /tmp/composer-project (this may take a while). -- 62.34s
geerlingguy.solr : Download Solr. -------------------------------------- 43.38s
install extra packages ubuntu ------------------------------------------ 39.80s
geerlingguy.java : Ensure Java is installed. --------------------------- 38.10s
geerlingguy.php : Ensure PHP packages are installed. ------------------- 37.92s
geerlingguy.drupal : Install configured modules with drush. ------------ 35.92s
geerlingguy.mysql : Ensure MySQL packages are installed. --------------- 21.22s
install python --------------------------------------------------------- 16.29s
geerlingguy.drupal : Install Drupal with drush. ------------------------ 15.71s
geerlingguy.solr : Run Solr installation script. ----------------------- 13.35s
Islandora-Devops.drupal-openseadragon : Install Openseadragon with composer -- 12.79s
Islandora-Devops.tomcat8 : install tomcat8 ----------------------------- 12.47s
install aptitude ------------------------------------------------------- 12.46s
geerlingguy.solr : restart solr ----------------------------------------- 9.41s
geerlingguy.solr : restart solr ----------------------------------------- 9.17s
geerlingguy.apache : Ensure Apache is installed on Debian. -------------- 8.58s
Islandora-Devops.matomo : Expand Matomo. -------------------------------- 7.67s
geerlingguy.git : Ensure git is installed (Debian). --------------------- 5.97s
geerlingguy.solr : Create configured cores. ----------------------------- 5.91s
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by whikloj** [comment]
Hi @DonRichards 

You need to delete the contents of your roles/external directory to pull down the changed ansible roles.

See https://github.com/Islandora-CLAW/CLAW/issues/1016

**Comment by DonRichards** [comment]
That got me past that error and to the next error. Any thoughts on this? 

```terminal 
TASK [Install demo module (fail ok)] *******************************************
Wednesday 06 February 2019  14:51:40 -0500 (0:00:00.788)       0:24:54.729 ****
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/var/www/html/drupal/vendor/drush/drush/drush", "-y", "en", "islandora_demo"], "delta": "0:00:08.402781", "end": "2019-02-06 19:51:48.938071", "msg": "non-zero return code", "rc": 1, "start": "2019-02-06 19:51:40.535290", "stderr": "Error: Call to a member function getSchema() on null in /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php on line 383 #0 /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php(283): Drupal\\views\\EntityViewsData->mapFieldDefinition('node_field_data', 'content_transla...', Object(Drupal\\Core\\Field\\BaseFieldDefinition), Object(Drupal\\Core\\Entity\\Sql\\DefaultTableMapping), Array)\n#1 /var/www/html/drupal/web/core/modules/node/src/NodeViewsData.php(16): Drupal\\views\\EntityViewsData->getViewsData()\n#2 /var/www/html/drupal/web/core/modules/views/views.views.inc(170): Drupal\\node\\NodeViewsData->getViewsData()\n#3 [internal function]: views_views_data()\n#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('views_views_dat...', Array)\n#5 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(243): Drupal\\Core\\Extension\\ModuleHandler->invoke('views', 'views_data')\n#6 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(160): Drupal\\views\\ViewsData->getData()\n#7 /var/www/html/drupal/web/core/modules/views/src/Plugin/ViewsHandlerManager.php(85): Drupal\\views\\ViewsData->get('media_field_dat...')\n#8 /var/www/html/drupal/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(889): Drupal\\views\\Plugin\\ViewsHandlerManager->getHandler(Array, NULL)\n#9 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(1040): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->getHandlers('field')\n#10 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(898): Drupal\\views\\ViewExecutable->_initHandler('field', Array)\n#11 /var/www/html/drupal/web/modules/contrib/eva/eva.module(73): Drupal\\views\\ViewExecutable->initHandlers()\n#12 /var/www/html/drupal/web/modules/contrib/eva/eva.module(19): eva_get_views()\n#13 [internal function]: eva_entity_extra_field_info()\n#14 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('eva_entity_extr...', Array)\n#15 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(610): Drupal\\Core\\Extension\\ModuleHandler->invokeAll('entity_extra_fi...')\n#16 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityManager.php(345): Drupal\\Core\\Entity\\EntityFieldManager->getExtraFields('media', 'image')\n#17 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(160): Drupal\\Core\\Entity\\EntityManager->getExtraFields('media', 'image')\n#18 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(143): Drupal\\Core\\Entity\\EntityDisplayBase->init()\n#19 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(175): Drupal\\Core\\Entity\\EntityDisplayBase->__construct(Array, 'entity_view_dis...')\n#20 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(359): Drupal\\Core\\Entity\\Entity\\EntityViewDisplay->__construct(Array, 'entity_view_dis...')\n#21 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(430): Drupal\\Core\\Entity\\EntityStorageBase->mapFromStorageRecords(Array)\n#22 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(405): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->_doCreateFromStorageRecord(Array)\n#23 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(329): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->createFromStorageRecord(Array)\n#24 /var/www/html/drupal/web/modules/contrib/features/src/FeaturesConfigInstaller.php(106): Drupal\\Core\\Config\\ConfigInstaller->createConfiguration('', Array)\n#25 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(132): Drupal\\features\\FeaturesConfigInstaller->createConfiguration('', Array)\n#26 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(268): Drupal\\Core\\Config\\ConfigInstaller->installDefaultConfig('module', 'islandora_demo')\n#27 /var/www/html/drupal/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, true)\n#28 /var/www/html/drupal/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(79): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, true)\n#29 [internal function]: Drush\\Drupal\\Commands\\pm\\PmCommands->enable(Array, Array)\n#30 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)\n#31 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\\AnnotatedCommand\\CommandProcessor->runCommandCallback(Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#32 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\\AnnotatedCommand\\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#33 /var/www/html/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\\AnnotatedCommand\\CommandProcessor->process(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput), Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#34 /var/www/html/drupal/vendor/symfony/console/Command/Command.php(251): Consolidation\\AnnotatedCommand\\AnnotatedCommand->execute(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#35 /var/www/html/drupal/vendor/symfony/console/Application.php(964): Symfony\\Component\\Console\\Command\\Command->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#36 /var/www/html/drupal/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Consolidation\\AnnotatedCommand\\AnnotatedCommand), Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#37 /var/www/html/drupal/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#38 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\\Component\\Console\\Application->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#39 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\\Runtime\\Runtime->doRun(Array)\n#40 /var/www/html/drupal/vendor/drush/drush/drush.php(66): Drush\\Runtime\\Runtime->run(Array)\n#41 /var/www/html/drupal/vendor/drush/drush/drush(4): require('/var/www/html/d...')\n#42 {main}\n [error]  Drush command terminated abnormally due to an unrecoverable error. ", "stderr_lines": ["Error: Call to a member function getSchema() on null in /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php on line 383 #0 /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php(283): Drupal\\views\\EntityViewsData->mapFieldDefinition('node_field_data', 'content_transla...', Object(Drupal\\Core\\Field\\BaseFieldDefinition), Object(Drupal\\Core\\Entity\\Sql\\DefaultTableMapping), Array)", "#1 /var/www/html/drupal/web/core/modules/node/src/NodeViewsData.php(16): Drupal\\views\\EntityViewsData->getViewsData()", "#2 /var/www/html/drupal/web/core/modules/views/views.views.inc(170): Drupal\\node\\NodeViewsData->getViewsData()", "#3 [internal function]: views_views_data()", "#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('views_views_dat...', Array)", "#5 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(243): Drupal\\Core\\Extension\\ModuleHandler->invoke('views', 'views_data')", "#6 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(160): Drupal\\views\\ViewsData->getData()", "#7 /var/www/html/drupal/web/core/modules/views/src/Plugin/ViewsHandlerManager.php(85): Drupal\\views\\ViewsData->get('media_field_dat...')", "#8 /var/www/html/drupal/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(889): Drupal\\views\\Plugin\\ViewsHandlerManager->getHandler(Array, NULL)", "#9 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(1040): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->getHandlers('field')", "#10 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(898): Drupal\\views\\ViewExecutable->_initHandler('field', Array)", "#11 /var/www/html/drupal/web/modules/contrib/eva/eva.module(73): Drupal\\views\\ViewExecutable->initHandlers()", "#12 /var/www/html/drupal/web/modules/contrib/eva/eva.module(19): eva_get_views()", "#13 [internal function]: eva_entity_extra_field_info()", "#14 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('eva_entity_extr...', Array)", "#15 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(610): Drupal\\Core\\Extension\\ModuleHandler->invokeAll('entity_extra_fi...')", "#16 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityManager.php(345): Drupal\\Core\\Entity\\EntityFieldManager->getExtraFields('media', 'image')", "#17 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(160): Drupal\\Core\\Entity\\EntityManager->getExtraFields('media', 'image')", "#18 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(143): Drupal\\Core\\Entity\\EntityDisplayBase->init()", "#19 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(175): Drupal\\Core\\Entity\\EntityDisplayBase->__construct(Array, 'entity_view_dis...')", "#20 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(359): Drupal\\Core\\Entity\\Entity\\EntityViewDisplay->__construct(Array, 'entity_view_dis...')", "#21 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(430): Drupal\\Core\\Entity\\EntityStorageBase->mapFromStorageRecords(Array)", "#22 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(405): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->_doCreateFromStorageRecord(Array)", "#23 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(329): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->createFromStorageRecord(Array)", "#24 /var/www/html/drupal/web/modules/contrib/features/src/FeaturesConfigInstaller.php(106): Drupal\\Core\\Config\\ConfigInstaller->createConfiguration('', Array)", "#25 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(132): Drupal\\features\\FeaturesConfigInstaller->createConfiguration('', Array)", "#26 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(268): Drupal\\Core\\Config\\ConfigInstaller->installDefaultConfig('module', 'islandora_demo')", "#27 /var/www/html/drupal/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, true)", "#28 /var/www/html/drupal/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(79): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, true)", "#29 [internal function]: Drush\\Drupal\\Commands\\pm\\PmCommands->enable(Array, Array)", "#30 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)", "#31 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\\AnnotatedCommand\\CommandProcessor->runCommandCallback(Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#32 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\\AnnotatedCommand\\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#33 /var/www/html/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\\AnnotatedCommand\\CommandProcessor->process(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput), Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#34 /var/www/html/drupal/vendor/symfony/console/Command/Command.php(251): Consolidation\\AnnotatedCommand\\AnnotatedCommand->execute(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#35 /var/www/html/drupal/vendor/symfony/console/Application.php(964): Symfony\\Component\\Console\\Command\\Command->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#36 /var/www/html/drupal/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Consolidation\\AnnotatedCommand\\AnnotatedCommand), Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#37 /var/www/html/drupal/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#38 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\\Component\\Console\\Application->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#39 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\\Runtime\\Runtime->doRun(Array)", "#40 /var/www/html/drupal/vendor/drush/drush/drush.php(66): Drush\\Runtime\\Runtime->run(Array)", "#41 /var/www/html/drupal/vendor/drush/drush/drush(4): require('/var/www/html/d...')", "#42 {main}", " [error]  Drush command terminated abnormally due to an unrecoverable error. "], "stdout": "The following module(s) will be enabled: islandora_demo, field_group, field_permissions, islandora_image, islandora_video\n\n // Do you want to continue?: yes.                                              \n\nError: Call to a member function getSchema() on null in Drupal\\views\\EntityViewsData->mapFieldDefinition() (line 383 of /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php).", "stdout_lines": ["The following module(s) will be enabled: islandora_demo, field_group, field_permissions, islandora_image, islandora_video", "", " // Do you want to continue?: yes.                                              ", "", "Error: Call to a member function getSchema() on null in Drupal\\views\\EntityViewsData->mapFieldDefinition() (line 383 of /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php)."]}
...ignoring
```

**Comment by dannylamb** [comment]
Due to some Drupal 8 quirks, we have to install, then update the db, then uninstall and re-install in order to make content translation work.  So what you're seeing is expected.  It says `(fail ok)` on the one that's supposed to fail.  If you make it past that without error, you're good.

**Comment by DonRichards** [comment]
Looks good!!
