### ISSUE TITLE
Failed delivery messages filling up camel logs

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-CLAW/CLAW#1029]
My camel and karaf logs are filling up with "Failed delivery" messages.
```
2019-02-20 16:04:51,146 | DEBUG | Consumer[fedora] | SendProcessor                    | 84 - org.apache.camel.camel-core - 2.19.2 | >>>> fcrepo://http://localhost:8080/fcrepo/rest?accept=application%2Fn-triples&preferInclude=&preferOmit=http%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23PreferContainment Exchange[ID-claw-46709-1550678644819-2-1]
2019-02-20 16:04:51,147 | DEBUG | Consumer[fedora] | BlueprintPropertiesParser        | 84 - org.apache.camel.camel-core - 2.19.2 | Blueprint parsed property key: error.maxRedeliveries as value: 10
2019-02-20 16:04:51,147 | DEBUG | Consumer[fedora] | BlueprintPropertiesParser        | 84 - org.apache.camel.camel-core - 2.19.2 | Delegate property parser parsed the property key: error.maxRedeliveries as value: 10
2019-02-20 16:04:51,147 | DEBUG | Consumer[fedora] | BlueprintCamelContext            | 84 - org.apache.camel.camel-core - 2.19.2 | Resolved text: {{error.maxRedeliveries}} -> 10
2019-02-20 16:04:51,147 | DEBUG | Consumer[fedora] | DefaultErrorHandler              | 84 - org.apache.camel.camel-core - 2.19.2 | Failed delivery for (MessageId: ID:claw-39768-1550678662905-5:1:1:1:1 on ExchangeId: ID-claw-46709-1550678644819-2-1). On delivery attempt: 10 caught: org.fcrepo.client.FcrepoOperationFailedException: HTTP operation failed invoking urn:uuid:b5fb376f-1709-4125-9068-03305c80d174 with statusCode: -1 and message: URI does not specify a valid host name: urn:uuid:b5fb376f-1709-4125-9068-03305c80d174
2019-02-20 16:04:51,149 | ERROR | Consumer[fedora] | DefaultErrorHandler              | 84 - org.apache.camel.camel-core - 2.19.2 | Failed delivery for (MessageId: ID:claw-39768-1550678662905-5:1:1:1:1 on ExchangeId: ID-claw-46709-1550678644819-2-1). Exhausted after delivery attempt: 11 caught: org.fcrepo.client.FcrepoOperationFailedException: HTTP operation failed invoking urn:uuid:b5fb376f-1709-4125-9068-03305c80d174 with statusCode: -1 and message: URI does not specify a valid host name: urn:uuid:b5fb376f-1709-4125-9068-03305c80d174. Processed by failure processor: FatalFallbackErrorHandler[Channel[Log(FcrepoTriplestoreUpdater)[Index Routing Error: ${routeId}]]]

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[FcrepoTriplestoreR] [FcrepoTriplestoreR] [activemq://topic:fedora                                                       ] [     10134]
[FcrepoTriplestoreR] [process9          ] [Processor@0x435011c1                                                          ] [        55]
[FcrepoTriplestoreR] [choice10          ] [when[{(header{header(CamelFcrepoEventType)} contains http://fedora.info/defini] [     10039]
[FcrepoTriplestoreR] [to21              ] [direct:index.triplestore                                                      ] [     10032]
[FcrepoTriplestoreI] [filter1           ] [filter[{not (in ([(header{header(CamelFcrepoUri)} startsWith constant{http://l] [     10032]
[FcrepoTriplestoreI] [removeHeaders2    ] [removeHeaders[CamelHttp*]                                                     ] [         0]
[FcrepoTriplestoreI] [choice11          ] [when[simple{Simple: {{indexing.predicate}} != 'true'}]choice[]                ] [     10031]
[FcrepoTriplestoreI] [to23              ] [direct:update.triplestore                                                     ] [     10029]
[FcrepoTriplestoreU] [setHeader10       ] [setHeader[CamelFcrepoNamedGraph]                                              ] [         0]
[FcrepoTriplestoreU] [to28              ] [fcrepo:{{fcrepo.baseUrl}}?accept=application/n-triples&preferOmit={{prefer.omi] [     10028]
[FcrepoTriplestoreU] [log1              ] [log                                                                           ] [         0]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
org.fcrepo.client.FcrepoOperationFailedException: HTTP operation failed invoking urn:uuid:b5fb376f-1709-4125-9068-03305c80d174 with statusCode: -1 and message: URI does not specify a valid host name: urn:uuid:b5fb376f-1709-4125-9068-03305c80d174
        at org.fcrepo.client.FcrepoClient.executeRequest(FcrepoClient.java:219)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
        at org.fcrepo.client.FcrepoClient.executeRequest(FcrepoClient.java:205)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
        at org.fcrepo.client.RequestBuilder.perform(RequestBuilder.java:78)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
        at org.fcrepo.camel.FcrepoProducer.getMetadataUri(FcrepoProducer.java:251)[147:org.fcrepo.camel.fcrepo-camel:4.5.0]
        at org.fcrepo.camel.FcrepoProducer.getUri(FcrepoProducer.java:225)[147:org.fcrepo.camel.fcrepo-camel:4.5.0]
        at org.fcrepo.camel.FcrepoProducer.doRequest(FcrepoProducer.java:194)[147:org.fcrepo.camel.fcrepo-camel:4.5.0]
        at org.fcrepo.camel.FcrepoProducer.process(FcrepoProducer.java:156)[147:org.fcrepo.camel.fcrepo-camel:4.5.0]
        at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:117)[84:org.apache.camel.camel-core:2.19.2]

        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97)[84:org.apache.camel.camel-core:2.19.2]
        at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112)[90:org.apache.camel.camel-jms:2.19.2]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721)[117:org.apache.servicemix.bundles.spring-jms:4.2.8.RELEASE_1]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681)[117:org.apache.servicemix.bundles.spring-jms:4.2.8.RELEASE_1]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)[117:org.apache.servicemix.bundles.spring-jms:4.2.8.RELEASE_1]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:313)[117:org.apache.servicemix.bundles.spring-jms:4.2.8.RELEASE_1]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:251)[117:org.apache.servicemix.bundles.spring-jms:4.2.8.RELEASE_1]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1164)[117:org.apache.servicemix.bundles.spring-jms:4.2.8.RELEASE_1]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1156)[117:org.apache.servicemix.bundles.spring-jms:4.2.8.RELEASE_1]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1053)[117:org.apache.servicemix.bundles.spring-jms:4.2.8.RELEASE_1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_191]
2019-02-20 16:04:51,150 | DEBUG | Consumer[fedora] | Pipeline                         | 84 - org.apache.camel.camel-core - 2.19.2 | Message exchange has failed: so breaking out of pipeline for exchange: Exchange[ID-claw-46709-1550678644819-2-1] Exception: org.fcrepo.client.FcrepoOperationFailedException: HTTP operation failed invoking urn:uuid:b5fb376f-1709-4125-9068-03305c80d174 with statusCode: -1 and message: URI does not specify a valid host name: urn:uuid:b5fb376f-1709-4125-9068-03305c80d174
```

These messages don't appear to stem from anything I'm doing on the Drupal side, so I think Fedora is up to something, but I don't know what. The catalina logs aren't showing anything related to this. This is happening both on my vagrant dev environment and our larger dev site. 

Aside from the fact that a standard installation shouldn't be throwing errors, it is happening so much that it rolled off any errors from the batch load that failed last night. (Yes, camel.log through camel.log.10 are all from this morning...)

**Comment by whikloj** [comment]
This is probably that the current fcrepo-camel-toolbox triplestore indexer is not working with the new ActivityStreams output by Fedora 5. 

You can edit your `$KARAF_HOME/etc/org.fcrepo.camel.indexing.triplestore.cfg` and change the line `error.maxRedeliveries=10` to `error.maxRedeliveries=1`.

**Comment by dannylamb** [comment]
@seth-shaw-unlv I also tend to just disable it all after the box spins up. From inside karaf:

- `feature:uninstall fcrepo-api-x`
- `feature:uninstall fcrepo-indexing-triplestore`
- `feature:install fcrepo-service-activemq`

does the trick.

**Comment by seth-shaw-unlv** [comment]
Considering this and the [Fedora 5 API-X is broken issue](https://logs.woh.ca/islandora/2019-02-07#490183;), perhaps we should have Fedora 4 as the default installed version for the time being?

**Comment by dannylamb** [comment]
I'd rather we just skip deploying api-x for the time being than move back to Fedora 4.  There's significant enough changes I'd rather avoid all the reverting.

**Comment by seth-shaw-unlv** [comment]
So, can setup the claw-playbook skip deploying it for us? Ideally as a configurable option?

**Comment by dannylamb** [comment]
It may come down to simply not requiring a role in requirements.yml, but I"ll need to look further.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-Devops/claw-playbook/pull/100
