### ISSUE TITLE
Figure out how to switch neatly between CENT and Ubuntu

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#746]
There has to be a way to do this without hacking up the Vagrantfile every time.  Check out how https://github.com/geerlingguy/drupal-vm does it and see if it can be applied to claw-playbook.

**Comment by dannylamb** [comment]
Looks like you can load yml files in Ruby and just use it in the Vagrantfile: https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile#L23

**Comment by dannylamb** [comment]
@ajs6f @DigitLib @Natkeeran @jonathangreen @whikloj 

Looking at this more closely, we've already got mechanisms if we want to take it as an environment variable.  How about we just do that plus put comments in the vagrantfile saying that 'centos/7' is available?

**Comment by dannylamb** [comment]
And README update

**Comment by whikloj** [comment]
I am fine with using an environment variable to choose the OS and version. 👍

**Comment by ajs6f** [comment]
Works for me, 💯

**Comment by dannylamb** [comment]
Also looks like shared folders are crapping out because guest additions aren't installed.  Were they already on ubuntu/xenial64 or something?  I don't see us installing them ourselves in the code anywhere.

**Comment by ajs6f** [comment]
Dunno how relevant this is, but [here](https://seven.centos.org/2017/07/updated-centos-vagrant-images-available-v1706-01/) it saith:

> The VirtualBox Guest Additions are not preinstalled; if you need them for shared folders, please install the vagrant-vbguest plugin and add the following line to your Vagrantfile:
```
config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
```
> We recommend using NFS instead of VirtualBox shared folders if possible; you can also use the vagrant-sshfs plugin, which, unlike NFS, works on all operating systems.

**Comment by dannylamb** [comment]
:(

```bash
daniel@daniel-Latitude-3560:~/Code/Environments/claw-playbook$ vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
/usr/lib/ruby/2.3.0/rubygems/specification.rb:946:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:231:in `internal_install'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:102:in `install'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:14:in `action'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `each'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
	from /usr/bin/vagrant:173:in `<main>'

```

**Comment by ajs6f** [comment]
Don't blame me-- I don't like Ruby to begin with. :)

**Comment by dannylamb** [comment]
Initial searches have yielded non-working workarounds, so I'm updating everything and seeing what gives.

**Comment by dannylamb** [comment]
Still got nothing on this.  But... if i short circuit to `/vagrant` for centos, it at least will bring up a box with `vagrant up --no-provision`.  I'll issue a PR and we can sort it out from there if someone knows something better.

**Comment by dannylamb** [comment]
Well, turns out I was mistaken.  The box would provision but you couldn't `vagrant ssh` in!

I'm figuring it out now, but looks like centos uses keys by default and doesn't like whatever we're doing.  Forcing it to use password authentication with `vagrant` as the password (which usually works) doesn't.

**Comment by dannylamb** [comment]
Alright, I think I've got this sorted out.  So there were two issues going on.

1. Couldn't install virtualbox-vbguest plugin
    1. Turns out I just needed to update Vagrant.  I was on 1.8.1, and updated to 2.0.1.  Works fine now.
1. Couldn't ssh in
    1. Centos has password ssh disabled by default, since everyone knows it's just `vagrant/vagrant`.  You need to manually pass in the enviroment variable for centos when `vagrant ssh`'ing as well, or it's going to default t what Ubuntu does.  If you don't want to pass in the environment variable every time, you'll need to either export it to your shell beforehand or hack up the vagrantfile.

**Comment by dannylamb** [comment]
^^ PR is up!

**Comment by DigitLib** [comment]
@dannylamb Couldn't install virtualbox-vbguest plugin

    Turns out I just needed to update Vagrant. I was on 1.8.1, and updated to 2.0.1. Works fine now.

After update Vagrant to 2.0.1 got:

Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 home_centos_islandora /home/centos/islandora

The error output from the command was:

mount: unknown filesystem type 'vboxsf'

**Comment by whikloj** [comment]
I really think we need to start testing and specifying a Vagrant version range.
https://www.vagrantup.com/docs/vagrantfile/vagrant_version.html

**Comment by dannylamb** [comment]
@DigitLib Thanks for testing.  I'm glad to hear you could get it working.

@whikloj That seems easy enough to add.  The README says 1.8.5+. Think that's still valid?

**Comment by dannylamb** [comment]
e.g. anyone out there with 1.8.5 that can verify the `virtualbox-vbguest` plugin still installs?

**Comment by whikloj** [comment]
I am still running vagrant 1.8.5, I am assuming the plugin installs as I can get the playbook up and running.

**Comment by whikloj** [comment]
@dannylamb also I would add a bottom and top end to the vagrant range, when a new version comes out we could test _before_ some tries to run it. 😄

**Comment by dannylamb** [comment]
top ranges?  preposterous.

i'll update the PR.

**Comment by dannylamb** [comment]
@whikloj Pushed.  Check it out.  You or @DigitLib are free to merge if you're satisfied with it.

**Comment by dannylamb** [comment]
@whikloj @DigitLib nudge.

If this is acceptable, please merge it in.  @DigitLib has also tested https://github.com/Islandora-Devops/claw-playbook/pull/27, which relies on this.  I'd like to get them both in so https://github.com/Islandora-CLAW/CLAW/issues/750 and https://github.com/Islandora-CLAW/CLAW/issues/751 can get worked on.

**Comment by dannylamb** [comment]
@whikloj https://github.com/Islandora-Devops/claw-playbook/pull/26?  27 was supposed to depend on it.

**Comment by jonathangreen** [comment]
This this is pretty well closed by https://github.com/Islandora-Devops/claw-playbook/pull/29. Anyone opposed to closing?
