### ISSUE TITLE
Fedora sync fails in subdomain configuration (CLAW-playbook)

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#756]
Deploying to a VM with IP as the hostname syncs the Drupal content to Fedora. However, when deployed to VM with subdomain.maindomain.ca as the hostname fails.

The issue seems to be here: https://github.com/Islandora-CLAW/Crayfish/blob/master/Milliner/src/Converter/DrupalEntityConverter.php#L55

The path variable it gets is not correct.  This seems to differ per configuration (vagrant vs ip vs subdomain).  Adding `$path = "subdomain." . $path;` seems to be a workaround!

### 
```java
	public static void main(String[] args) {
		// Prints "Hello, World" to the terminal window.
		String uri = "http://aaa-beta.subd.maindomain.ca:8000/node/51";
		String baseUrl = "http://localhost:8000";
		String output = getPath(uri, baseUrl);
		System.out.println("preProcessed url " + output);
		// Outputs preProcessed url maindomain.ca:8000/node/51
	}

	public static String getPath(final String uri, final String baseUrl) {
		final String sanitized = addTrailingSlash(baseUrl);
		System.out.println("trailing slashes " + sanitized);
		// Outputs trailing slashes http://localhost:8000/
		return uri.substring(uri.lastIndexOf(sanitized) + sanitized.length());
	}

	private static String addTrailingSlash(final String str) {
		final String trimmed = str.trim();
		if (!trimmed.endsWith("/")) {
			return trimmed + "/";
		}
		return trimmed;
	}
```
### Gemini Database
```
mysql> select * from Gemini;
+----+--------------------------+-------------------------------------------------------------------+
| id | drupal                   | fedora                                                            |
+----+--------------------------+-------------------------------------------------------------------+
|  1 | maindomain.ca:8000/node/29 | 8080/fcrepo/rest/53/1d/28/13/531d2813-b39f-4e3c-8f22-6b2c33558a83 |
|  2 | maindomain.ca:8000/node/30 | 8080/fcrepo/rest/5b/4b/d8/a6/5b4bd8a6-29db-4594-a3f4-d617000190c9 |
|  3 | maindomain.ca:8000/node/31 | 8080/fcrepo/rest/ad/0c/3e/90/ad0c3e90-bb9f-4ae2-a6c9-b2efd2c4c80c |
|  4 | maindomain.ca:8000/node/32 | 8080/fcrepo/rest/87/b9/28/59/87b92859-292b-450e-851e-6aaf94a2636a |
|  5 | maindomain.ca:8000/node/33 | 8080/fcrepo/rest/79/d1/f5/c4/79d1f5c4-108d-4984-b11e-cd27af58d76e |
|  6 | maindomain.ca:8000/node/34 | 8080/fcrepo/rest/3e/3d/e4/92/3e3de492-1ad1-4d3d-bf37-e2bd9da11643 |
|  7 | maindomain.ca:8000/node/35 | 8080/fcrepo/rest/60/e9/9e/5a/60e99e5a-14f5-4c7e-86a3-5d3741193743 |
+----+--------------------------+-------------------------------------------------------------------+
```

### Milliner Log
```
{"_controller":"milliner.controller:createRdf","drupal_entity":"maindomain.ca:8000/node/14","_route":"POST_rdf_drupal_entity"},"request_uri":"http://localhost:8000/milliner/rdf/maindomain.ca:8000/node/14","method":"POST"} []
[2017-11-13 13:47:25] app.DEBUG: Checking for guard authentication credentials. {"firewall_key":"default","authenticators":1} []
[2017-11-13 13:47:25] app.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"default","authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2017-11-13 13:47:25] crayfish.syn.jwt_authentication.DEBUG: Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1MTA1OTg4MzksImV4cCI6MTUxMDYwNjAzOSwidWlkIjoiMSIsIm5hbWUiOiJhZG1pbiIsInJvbGVzIjpbImF1dGhlbnRpY2F0ZWQiLCJhZG1pbmlzdHJhdG9yIl0sInVybCI6Imh0dHBzOlwvXC9kc3UtYmV0YS51dHNjLnV0b3JvbnRvLmNhOjgwMDAifQ.iE9skammRkNULvjlYDhP1_LeT0s5w67xbHOH-ad1ovSaG93fqY2m7NhZLIwjy_czsfbq9MbWkj0Ss6B96KRI9fIcBW_HbBoZ0AJqH9U_atSOAwhwpCYY0z_ijHtZs5wrVqido3wXeBhNii-S8HB4wfjKE4zJPa2lXgZLhsUh20aor7CvsviVPtI_CRYXL8KUj43kp9e7BbV7N8cu25BkHk6rB1jXg8a6xf5e75VFgyQ_0qYLew9c39ciKn7tlEaBXjgpiaoM8umGWchoNNPaYEq2-t98bzUHN-CiN_YygzTR1TQ-bm8Ghzvl5O647s2MV4mR8LpMs4k7ppP5Jh_SiQ [] []
[2017-11-13 13:47:25] app.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"default","authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2017-11-13 13:47:25] app.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"admin\", authenticated=true, roles=\"authenticated, administrator\"))","authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2017-11-13 13:47:25] app.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2017-11-13 13:47:25] app.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2017-11-13 13:47:25] app.DEBUG: > POST /milliner/rdf/maindomain.ca:8000/node/14 [] []
[2017-11-13 13:47:25] app.CRITICAL: GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to onto.ca port 8000: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (uncaught exception) at /var/www/html/Crayfish/Milliner/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 186 {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 7: Failed to connect to onto.ca port 8000: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at /var/www/html/Crayfish/Milliner/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186)"} []
[2017-11-13 13:47:25] app.DEBUG: < 500 [] []
```
### Karaf Log
```
2017-11-13 12:42:42,876 | DEBUG | g-fcrepo-create] | HttpProducer                     | 86 - org.apache.camel.camel-http4 - 2.19.2 | Executing http POST method: http://localhost:8000/milliner/rdf/maindomain.ca:8000/node/10
2017-11-13 12:42:42,913 | DEBUG | g-fcrepo-create] | HttpProducer                     | 86 - org.apache.camel.camel-http4 - 2.19.2 | Http responseCode: 500
2017-11-13 12:42:42,917 | DEBUG | g-fcrepo-create] | DeadLetterChannel                | 84 - org.apache.camel.camel-core - 2.19.2 | Failed delivery for (MessageId: ID-dsu-beta-34972-1510594209563-6-13 on ExchangeId: ID-dsu-beta-34972-1510594209563-6-11). On delivery attempt: 5 caught: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:8000/milliner/rdf/maindomain.ca:8000/node/10 with statusCode: 500
2017-11-13 12:42:42,918 | DEBUG | g-fcrepo-create] | SendProcessor                    | 84 - org.apache.camel.camel-core - 2.19.2 | >>>> direct://create-rdf-log-error Exchange[ID-dsu-beta-34972-1510594209563-6-11]
2017-11-13 12:42:42,920 | ERROR | g-fcrepo-create] | FcrepoIndexer                    | 166 - ca.islandora.alpaca.islandora-indexing-fcrepo - 0.3.1.SNAPSHOT | org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:8000/milliner/rdf/maindomain.ca:8000/node/10 with statusCode: 500
	at org.apache.camel.component.http4.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:312)
	at org.apache.camel.component.http4.HttpProducer.process(HttpProducer.java:207)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendDynamicProcessor$1.doInAsyncProducer(SendDynamicProcessor.java:124)
	at org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:436)
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:119)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.FilterProcessor.process(FilterProcessor.java:57)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97)
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:313)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:251)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1164)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1156)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1053)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:8000/milliner/rdf/utoronto.ca:8000/node/10 with statusCode: 500
		... 31 more
		Suppressed: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:8000/milliner/rdf/utoronto.ca:8000/node/10 with statusCode: 500
			... 31 more
			Suppressed: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:8000/milliner/rdf/utoronto.ca:8000/node/10 with statusCode: 500
				... 31 more
				Suppressed: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:8000/milliner/rdf/utoronto.ca:8000/node/10 with statusCode: 500
					... 31 more
					Suppressed: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://localhost:8000/milliner/rdf/utoronto.ca:8000/node/10 with statusCode: 500
						... 31 more
```

**Comment by Natkeeran** [comment]
@whikloj @dannylamb 
I am closing this issue.  Merging of 640 and recent changes have addressed this issue.  Tested in [claw-playbook](https://github.com/Islandora-Devops/claw-playbook/commit/abf4d8fbccb6e0d76476dbffa5ac0449a38ac662).
