### ISSUE TITLE
Ansible crash out on geerlingguy.drupal : Install configured modules with drush

### ISSUE THREAD

**Issue by ajs6f** [Islandora-CLAW/CLAW#885]
I'm getting a really nice Ansible/Vagrant install (using Debian) up to the abovementioned task. I'm going to put the trace in a comment below because it's a bit of a monster.

**Comment by ajs6f** [comment]
```
TASK [geerlingguy.drupal : Install configured modules with drush.] *************
Wednesday 25 July 2018  13:17:09 -0400 (0:00:55.044)       0:25:02.506 ********
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/var/www/html/drupal/vendor/drush/drush/drush", "pm-enable", "-y", "rdf", "responsive_image", "syslog", "serialization", "basic_auth", "rest", "simpletest", "restui", "devel", "search_api_solr", "search_api_solr_defaults", "facets", "islandora_core_feature", "islandora_demo_feature", "--root=/var/www/html/drupal/web"], "delta": "0:01:21.912087", "end": "2018-07-25 17:18:30.193519", "msg": "non-zero return code", "rc": 1, "start": "2018-07-25 17:17:08.281432", "stderr": "Error: Call to a member function getSchema() on null in /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php on line 383 #0 /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php(283): Drupal\\views\\EntityViewsData->mapFieldDefinition('node_field_data', 'content_transla...', Object(Drupal\\Core\\Field\\BaseFieldDefinition), Object(Drupal\\Core\\Entity\\Sql\\DefaultTableMapping), Array)\n#1 /var/www/html/drupal/web/core/modules/node/src/NodeViewsData.php(16): Drupal\\views\\EntityViewsData->getViewsData()\n#2 /var/www/html/drupal/web/core/modules/views/views.views.inc(170): Drupal\\node\\NodeViewsData->getViewsData()\n#3 [internal function]: views_views_data()\n#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(391): call_user_func_array('views_views_dat...', Array)\n#5 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(245): Drupal\\Core\\Extension\\ModuleHandler->invoke('views', 'views_data')\n#6 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(162): Drupal\\views\\ViewsData->getData()\n#7 /var/www/html/drupal/web/core/modules/views/src/Plugin/ViewsHandlerManager.php(85): Drupal\\views\\ViewsData->get('media_field_dat...')\n#8 /var/www/html/drupal/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(889): Drupal\\views\\Plugin\\ViewsHandlerManager->getHandler(Array, NULL)\n#9 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(1040): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->getHandlers('field')\n#10 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(898): Drupal\\views\\ViewExecutable->_initHandler('field', Array)\n#11 /var/www/html/drupal/web/modules/contrib/eva/eva.module(73): Drupal\\views\\ViewExecutable->initHandlers()\n#12 /var/www/html/drupal/web/modules/contrib/eva/eva.module(19): eva_get_views()\n#13 [internal function]: eva_entity_extra_field_info()\n#14 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(402): call_user_func_array('eva_entity_extr...', Array)\n#15 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(610): Drupal\\Core\\Extension\\ModuleHandler->invokeAll('entity_extra_fi...')\n#16 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityManager.php(345): Drupal\\Core\\Entity\\EntityFieldManager->getExtraFields('media', 'image')\n#17 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(160): Drupal\\Core\\Entity\\EntityManager->getExtraFields('media', 'image')\n#18 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(143): Drupal\\Core\\Entity\\EntityDisplayBase->init()\n#19 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(175): Drupal\\Core\\Entity\\EntityDisplayBase->__construct(Array, 'entity_view_dis...')\n#20 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(322): Drupal\\Core\\Entity\\Entity\\EntityViewDisplay->__construct(Array, 'entity_view_dis...')\n#21 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(459): Drupal\\Core\\Entity\\EntityStorageBase->mapFromStorageRecords(Array)\n#22 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(434): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->_doCreateFromStorageRecord(Array)\n#23 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(327): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->createFromStorageRecord(Array)\n#24 /var/www/html/drupal/web/modules/contrib/features/src/FeaturesConfigInstaller.php(106): Drupal\\Core\\Config\\ConfigInstaller->createConfiguration('', Array)\n#25 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(134): Drupal\\features\\FeaturesConfigInstaller->createConfiguration('', Array)\n#26 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(263): Drupal\\Core\\Config\\ConfigInstaller->installDefaultConfig('module', 'islandora_demo_...')\n#27 /var/www/html/drupal/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, true)\n#28 /var/www/html/drupal/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(79): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, true)\n#29 [internal function]: Drush\\Drupal\\Commands\\pm\\PmCommands->enable(Array, Array)\n#30 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)\n#31 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\\AnnotatedCommand\\CommandProcessor->runCommandCallback(Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#32 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\\AnnotatedCommand\\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#33 /var/www/html/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\\AnnotatedCommand\\CommandProcessor->process(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput), Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#34 /var/www/html/drupal/vendor/symfony/console/Command/Command.php(251): Consolidation\\AnnotatedCommand\\AnnotatedCommand->execute(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#35 /var/www/html/drupal/vendor/symfony/console/Application.php(964): Symfony\\Component\\Console\\Command\\Command->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#36 /var/www/html/drupal/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Consolidation\\AnnotatedCommand\\AnnotatedCommand), Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#37 /var/www/html/drupal/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#38 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\\Component\\Console\\Application->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#39 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\\Runtime\\Runtime->doRun(Array)\n#40 /var/www/html/drupal/vendor/drush/drush/drush.php(66): Drush\\Runtime\\Runtime->run(Array)\n#41 /var/www/html/drupal/vendor/drush/drush/drush(4): require('/var/www/html/d...')\n#42 {main}\n [error]  Drush command terminated abnormally due to an unrecoverable error. ", "stderr_lines": ["Error: Call to a member function getSchema() on null in /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php on line 383 #0 /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php(283): Drupal\\views\\EntityViewsData->mapFieldDefinition('node_field_data', 'content_transla...', Object(Drupal\\Core\\Field\\BaseFieldDefinition), Object(Drupal\\Core\\Entity\\Sql\\DefaultTableMapping), Array)", "#1 /var/www/html/drupal/web/core/modules/node/src/NodeViewsData.php(16): Drupal\\views\\EntityViewsData->getViewsData()", "#2 /var/www/html/drupal/web/core/modules/views/views.views.inc(170): Drupal\\node\\NodeViewsData->getViewsData()", "#3 [internal function]: views_views_data()", "#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(391): call_user_func_array('views_views_dat...', Array)", "#5 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(245): Drupal\\Core\\Extension\\ModuleHandler->invoke('views', 'views_data')", "#6 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(162): Drupal\\views\\ViewsData->getData()", "#7 /var/www/html/drupal/web/core/modules/views/src/Plugin/ViewsHandlerManager.php(85): Drupal\\views\\ViewsData->get('media_field_dat...')", "#8 /var/www/html/drupal/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(889): Drupal\\views\\Plugin\\ViewsHandlerManager->getHandler(Array, NULL)", "#9 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(1040): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->getHandlers('field')", "#10 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(898): Drupal\\views\\ViewExecutable->_initHandler('field', Array)", "#11 /var/www/html/drupal/web/modules/contrib/eva/eva.module(73): Drupal\\views\\ViewExecutable->initHandlers()", "#12 /var/www/html/drupal/web/modules/contrib/eva/eva.module(19): eva_get_views()", "#13 [internal function]: eva_entity_extra_field_info()", "#14 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(402): call_user_func_array('eva_entity_extr...', Array)", "#15 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(610): Drupal\\Core\\Extension\\ModuleHandler->invokeAll('entity_extra_fi...')", "#16 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityManager.php(345): Drupal\\Core\\Entity\\EntityFieldManager->getExtraFields('media', 'image')", "#17 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(160): Drupal\\Core\\Entity\\EntityManager->getExtraFields('media', 'image')", "#18 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(143): Drupal\\Core\\Entity\\EntityDisplayBase->init()", "#19 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(175): Drupal\\Core\\Entity\\EntityDisplayBase->__construct(Array, 'entity_view_dis...')", "#20 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(322): Drupal\\Core\\Entity\\Entity\\EntityViewDisplay->__construct(Array, 'entity_view_dis...')", "#21 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(459): Drupal\\Core\\Entity\\EntityStorageBase->mapFromStorageRecords(Array)", "#22 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(434): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->_doCreateFromStorageRecord(Array)", "#23 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(327): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->createFromStorageRecord(Array)", "#24 /var/www/html/drupal/web/modules/contrib/features/src/FeaturesConfigInstaller.php(106): Drupal\\Core\\Config\\ConfigInstaller->createConfiguration('', Array)", "#25 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(134): Drupal\\features\\FeaturesConfigInstaller->createConfiguration('', Array)", "#26 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(263): Drupal\\Core\\Config\\ConfigInstaller->installDefaultConfig('module', 'islandora_demo_...')", "#27 /var/www/html/drupal/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, true)", "#28 /var/www/html/drupal/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(79): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, true)", "#29 [internal function]: Drush\\Drupal\\Commands\\pm\\PmCommands->enable(Array, Array)", "#30 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)", "#31 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\\AnnotatedCommand\\CommandProcessor->runCommandCallback(Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#32 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\\AnnotatedCommand\\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#33 /var/www/html/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\\AnnotatedCommand\\CommandProcessor->process(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput), Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#34 /var/www/html/drupal/vendor/symfony/console/Command/Command.php(251): Consolidation\\AnnotatedCommand\\AnnotatedCommand->execute(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#35 /var/www/html/drupal/vendor/symfony/console/Application.php(964): Symfony\\Component\\Console\\Command\\Command->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#36 /var/www/html/drupal/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Consolidation\\AnnotatedCommand\\AnnotatedCommand), Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#37 /var/www/html/drupal/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#38 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\\Component\\Console\\Application->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#39 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\\Runtime\\Runtime->doRun(Array)", "#40 /var/www/html/drupal/vendor/drush/drush/drush.php(66): Drush\\Runtime\\Runtime->run(Array)", "#41 /var/www/html/drupal/vendor/drush/drush/drush(4): require('/var/www/html/d...')", "#42 {main}", " [error]  Drush command terminated abnormally due to an unrecoverable error. "], "stdout": "The following module(s) will be enabled: responsive_image, syslog, serialization, basic_auth, rest, simpletest, restui, devel, search_api_solr, search_api_solr_defaults, facets, islandora_core_feature, islandora_demo_feature, language, search_api, content_translation, eva, features, config_update, islandora, jsonld, hal, jwt, key, filehash, context_ui, context, action, media, prepopulate, features_ui, migrate_tools, migrate, migrate_plus, migrate_source_csv, islandora_image, openseadragon, libraries\n\n // Do you want to continue?: yes.                                              \n\nError: Call to a member function getSchema() on null in Drupal\\views\\EntityViewsData->mapFieldDefinition() (line 383 of /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php).", "stdout_lines": ["The following module(s) will be enabled: responsive_image, syslog, serialization, basic_auth, rest, simpletest, restui, devel, search_api_solr, search_api_solr_defaults, facets, islandora_core_feature, islandora_demo_feature, language, search_api, content_translation, eva, features, config_update, islandora, jsonld, hal, jwt, key, filehash, context_ui, context, action, media, prepopulate, features_ui, migrate_tools, migrate, migrate_plus, migrate_source_csv, islandora_image, openseadragon, libraries", "", " // Do you want to continue?: yes.                                              ", "", "Error: Call to a member function getSchema() on null in Drupal\\views\\EntityViewsData->mapFieldDefinition() (line 383 of /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php)."]}
```

**Comment by ajs6f** [comment]
Maybe I should file this at the [geerlingguy Drupal role](https://github.com/geerlingguy/ansible-role-drupal)?

**Comment by dannylamb** [comment]
@ajs6f I've actually got a PR up for this right now: https://github.com/Islandora-Devops/claw-playbook/pull/71

**Comment by ajs6f** [comment]
My word, @dannylamb -- you're so fast, you solved the prob before I had it! Going to test right now...

**Comment by dannylamb** [comment]
@ajs6f it's due to https://github.com/Islandora-CLAW/CLAW/issues/873.  Don't file an issue with @geerlingguy.  It's definitely us.  Well... it's definitely Drupal, actually https://www.drupal.org/node/2599228

**Comment by dannylamb** [comment]
Oh it's gross what I do, but that's the only way Drupal would like it.

This will supposedly be fixed in Drupal 8.7, so we'll have to live with it like this for about six months.
