### ISSUE TITLE
taxonomy_term.resource_types.default already exists

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/CLAW#924]
Seeing the following ansible error.  This maybe a regression issue related to this merge: https://github.com/Islandora-CLAW/islandora_demo/pull/2.  

```
TASK [Import feature] *****************************************************************************************************************************
Monday 17 September 2018  15:05:28 -0400 (0:00:09.561)       0:17:26.852 ****** 
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/var/www/html/drupal/vendor/drush/drush/drush", "-y", "fim", "--bundle=islandora", "islandora_demo"], "delta": "0:00:02.403283", "end": "2018-09-17 19:05:30.627884", "msg": "non-zero return code", "rc": 1, "start": "2018-09-17 19:05:28.224601", "stderr": "\nIn EntityStorageBase.php line 462:\n                                                                               \n  'entity_view_display' entity with ID 'taxonomy_term.resource_types.default'  \n   already exists.                                                             \n                                                                               \n\nfeatures:import [--bundle [BUNDLE]] [--force [FORCE]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> <feature>", "stderr_lines": ["", "In EntityStorageBase.php line 462:", "                                                                               ", "  'entity_view_display' entity with ID 'taxonomy_term.resource_types.default'  ", "   already exists.                                                             ", "                                                                               ", "", "features:import [--bundle [BUNDLE]] [--force [FORCE]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> <feature>"], "stdout": "\n // Do you really want to import islandora_demo :                               \n // core.entity_view_display.resource_types.default?: yes.                      \n\n // Do you really want to import islandora_demo :                               \n // core.entity_form_display.media.audio.default?: yes.                         \n\n // Do you really want to import islandora_demo :                               \n // core.entity_form_display.media.file.default?: yes.                          \n\n // Do you really want to import islandora_demo :                               \n // core.entity_form_display.media.image.default?: yes.                         \n\n // Do you really want to import islandora_demo :                               \n // core.entity_form_display.media.video.default?: yes.                         \n\n // Do you really want to import islandora_demo :                               \n // core.entity_form_display.node.islandora_object.default?: yes.               \n\n // Do you really want to import islandora_demo :                               \n // core.entity_view_display.media.audio.default?: yes.                         \n\n // Do you really want to import islandora_demo :                               \n // core.entity_view_display.media.file.default?: yes.                          \n\n // Do you really want to import islandora_demo :                               \n // core.entity_view_display.media.image.default?: yes.                         \n\n // Do you really want to import islandora_demo :                               \n // core.entity_view_display.media.video.default?: yes.                         \n\n // Do you really want to import islandora_demo :                               \n // core.entity_view_display.node.islandora_object.binary?: yes.                \n\n // Do you really want to import islandora_demo :                               \n // core.entity_view_display.node.islandora_object.default?: yes.               \n\n // Do you really want to import islandora_demo :                               \n // core.entity_view_display.node.islandora_object.open_seadragon?: yes.        \n\n // Do you really want to import islandora_demo :                               \n // core.entity_view_display.node.islandora_object.teaser?: yes.                \n\n // Do you really want to import islandora_demo :                               \n // field.field.node.islandora_object.field_edtf_date_created?: yes.            \n\n // Do you really want to import islandora_demo :                               \n // field.field.taxonomy_term.resource_types.field_external_authority_link?:    \n // yes.                                                                        \n\n // Do you really want to import islandora_demo :                               \n // field.storage.taxonomy_term.field_external_authority_link?: yes.            ", "stdout_lines": ["", " // Do you really want to import islandora_demo :                               ", " // core.entity_view_display.resource_types.default?: yes.                      ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_form_display.media.audio.default?: yes.                         ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_form_display.media.file.default?: yes.                          ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_form_display.media.image.default?: yes.                         ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_form_display.media.video.default?: yes.                         ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_form_display.node.islandora_object.default?: yes.               ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_view_display.media.audio.default?: yes.                         ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_view_display.media.file.default?: yes.                          ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_view_display.media.image.default?: yes.                         ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_view_display.media.video.default?: yes.                         ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_view_display.node.islandora_object.binary?: yes.                ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_view_display.node.islandora_object.default?: yes.               ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_view_display.node.islandora_object.open_seadragon?: yes.        ", "", " // Do you really want to import islandora_demo :                               ", " // core.entity_view_display.node.islandora_object.teaser?: yes.                ", "", " // Do you really want to import islandora_demo :                               ", " // field.field.node.islandora_object.field_edtf_date_created?: yes.            ", "", " // Do you really want to import islandora_demo :                               ", " // field.field.taxonomy_term.resource_types.field_external_authority_link?:    ", " // yes.                                                                        ", "", " // Do you really want to import islandora_demo :                               ", " // field.storage.taxonomy_term.field_external_authority_link?: yes.            "]}
```

**Comment by Natkeeran** [comment]
@dannylamb @seth-shaw-unlv 

Please take a look.  Islandora Feature is not installing via ansible.

**Comment by dannylamb** [comment]
@Natkeeran I think `core.entity_view_display.resource_types.default.yml` should be `core.entity_view_display.taxonomy_term.resource_types.default.yml`?

I'll try to sort out a local install before attempting something with ansible.

**Comment by dannylamb** [comment]
@Natkeeran That works for me locally, but can't really test with vagrant until it's merged and in packagist.

**Comment by Natkeeran** [comment]
@dannylamb Should we merge it and test.  I can test this after 12 pm.

**Comment by dannylamb** [comment]
@Natkeeran Go for it and I'll run a `vagrant up` to confirm as soon as it's merged.

**Comment by Natkeeran** [comment]
@dannylamb Actually, I had tried that yesterday.  That did not work for me!  But will try again.

**Comment by dannylamb** [comment]
@Natkeeran I'm not sure if it will resolve things 100%, there's likely a few more steps we'll have to make.  I ran into this yesterday when attempting to rebase my work for Islandora-CLAW/CLAW#888, and this got me a step further.

**Comment by dannylamb** [comment]
The fact that we're working around that crazy content translation/entity update bug isn't helping make diagnosis any easier, too.

**Comment by dannylamb** [comment]
@Natkeeran Now that I think about it, maybe I can do what we did with https://github.com/Islandora-CLAW/CLAW/issues/920 and push a branch to foundation's repo.  Then we can point claw-playbook at it and test.

**Comment by dannylamb** [comment]
@Natkeeran I pushed up https://github.com/Islandora-CLAW/islandora_demo/tree/issue-924 and am using it to test with claw-playbook.

**Comment by dannylamb** [comment]
@Natkeeran Tested with a fresh `vagrant up` and it installed just fine.

**Comment by Natkeeran** [comment]
@dannylamb 

I am assuming the following issue is related to the original translation related issue.

```
TASK [Install demo module (fail ok)] *******************************************
Tuesday 18 September 2018  13:21:06 -0400 (0:00:00.785)       0:18:44.393 ***** 
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/var/www/html/drupal/vendor/drush/drush/drush", "-y", "en", "islandora_demo"], "delta": "0:00:08.872326", "end": "2018-09-18 17:21:15.129637", "msg": "non-zero return code", "rc": 1, "start": "2018-09-18 17:21:06.257311", "stderr": "Error: Call to a member function getSchema() on null in /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php on line 383 #0 /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php(283): Drupal\\views\\EntityViewsData->mapFieldDefinition('node_field_data', 'content_transla...', Object(Drupal\\Core\\Field\\BaseFieldDefinition), Object(Drupal\\Core\\Entity\\Sql\\DefaultTableMapping), Array)\n#1 /var/www/html/drupal/web/core/modules/node/src/NodeViewsData.php(16): Drupal\\views\\EntityViewsData->getViewsData()\n#2 /var/www/html/drupal/web/core/modules/views/views.views.inc(170): Drupal\\node\\NodeViewsData->getViewsData()\n#3 [internal function]: views_views_data()\n#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('views_views_dat...', Array)\n#5 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(243): Drupal\\Core\\Extension\\ModuleHandler->invoke('views', 'views_data')\n#6 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(160): Drupal\\views\\ViewsData->getData()\n#7 /var/www/html/drupal/web/core/modules/views/src/Plugin/ViewsHandlerManager.php(85): Drupal\\views\\ViewsData->get('media_field_dat...')\n#8 /var/www/html/drupal/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(889): Drupal\\views\\Plugin\\ViewsHandlerManager->getHandler(Array, NULL)\n#9 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(1040): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->getHandlers('field')\n#10 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(898): Drupal\\views\\ViewExecutable->_initHandler('field', Array)\n#11 /var/www/html/drupal/web/modules/contrib/eva/eva.module(73): Drupal\\views\\ViewExecutable->initHandlers()\n#12 /var/www/html/drupal/web/modules/contrib/eva/eva.module(19): eva_get_views()\n#13 [internal function]: eva_entity_extra_field_info()\n#14 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('eva_entity_extr...', Array)\n#15 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(610): Drupal\\Core\\Extension\\ModuleHandler->invokeAll('entity_extra_fi...')\n#16 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityManager.php(345): Drupal\\Core\\Entity\\EntityFieldManager->getExtraFields('media', 'image')\n#17 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(160): Drupal\\Core\\Entity\\EntityManager->getExtraFields('media', 'image')\n#18 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(143): Drupal\\Core\\Entity\\EntityDisplayBase->init()\n#19 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(175): Drupal\\Core\\Entity\\EntityDisplayBase->__construct(Array, 'entity_view_dis...')\n#20 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(359): Drupal\\Core\\Entity\\Entity\\EntityViewDisplay->__construct(Array, 'entity_view_dis...')\n#21 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(430): Drupal\\Core\\Entity\\EntityStorageBase->mapFromStorageRecords(Array)\n#22 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(405): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->_doCreateFromStorageRecord(Array)\n#23 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(329): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->createFromStorageRecord(Array)\n#24 /var/www/html/drupal/web/modules/contrib/features/src/FeaturesConfigInstaller.php(106): Drupal\\Core\\Config\\ConfigInstaller->createConfiguration('', Array)\n#25 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(132): Drupal\\features\\FeaturesConfigInstaller->createConfiguration('', Array)\n#26 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(268): Drupal\\Core\\Config\\ConfigInstaller->installDefaultConfig('module', 'islandora_demo')\n#27 /var/www/html/drupal/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, true)\n#28 /var/www/html/drupal/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(79): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, true)\n#29 [internal function]: Drush\\Drupal\\Commands\\pm\\PmCommands->enable(Array, Array)\n#30 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)\n#31 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\\AnnotatedCommand\\CommandProcessor->runCommandCallback(Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#32 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\\AnnotatedCommand\\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#33 /var/www/html/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\\AnnotatedCommand\\CommandProcessor->process(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput), Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#34 /var/www/html/drupal/vendor/symfony/console/Command/Command.php(251): Consolidation\\AnnotatedCommand\\AnnotatedCommand->execute(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#35 /var/www/html/drupal/vendor/symfony/console/Application.php(964): Symfony\\Component\\Console\\Command\\Command->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#36 /var/www/html/drupal/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Consolidation\\AnnotatedCommand\\AnnotatedCommand), Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#37 /var/www/html/drupal/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#38 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\\Component\\Console\\Application->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#39 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\\Runtime\\Runtime->doRun(Array)\n#40 /var/www/html/drupal/vendor/drush/drush/drush.php(66): Drush\\Runtime\\Runtime->run(Array)\n#41 /var/www/html/drupal/vendor/drush/drush/drush(4): require('/var/www/html/d...')\n#42 {main}\n [error]  Drush command terminated abnormally due to an unrecoverable error. ", "stderr_lines": ["Error: Call to a member function getSchema() on null in /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php on line 383 #0 /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php(283): Drupal\\views\\EntityViewsData->mapFieldDefinition('node_field_data', 'content_transla...', Object(Drupal\\Core\\Field\\BaseFieldDefinition), Object(Drupal\\Core\\Entity\\Sql\\DefaultTableMapping), Array)", "#1 /var/www/html/drupal/web/core/modules/node/src/NodeViewsData.php(16): Drupal\\views\\EntityViewsData->getViewsData()", "#2 /var/www/html/drupal/web/core/modules/views/views.views.inc(170): Drupal\\node\\NodeViewsData->getViewsData()", "#3 [internal function]: views_views_data()", "#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('views_views_dat...', Array)", "#5 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(243): Drupal\\Core\\Extension\\ModuleHandler->invoke('views', 'views_data')", "#6 /var/www/html/drupal/web/core/modules/views/src/ViewsData.php(160): Drupal\\views\\ViewsData->getData()", "#7 /var/www/html/drupal/web/core/modules/views/src/Plugin/ViewsHandlerManager.php(85): Drupal\\views\\ViewsData->get('media_field_dat...')", "#8 /var/www/html/drupal/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(889): Drupal\\views\\Plugin\\ViewsHandlerManager->getHandler(Array, NULL)", "#9 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(1040): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->getHandlers('field')", "#10 /var/www/html/drupal/web/core/modules/views/src/ViewExecutable.php(898): Drupal\\views\\ViewExecutable->_initHandler('field', Array)", "#11 /var/www/html/drupal/web/modules/contrib/eva/eva.module(73): Drupal\\views\\ViewExecutable->initHandlers()", "#12 /var/www/html/drupal/web/modules/contrib/eva/eva.module(19): eva_get_views()", "#13 [internal function]: eva_entity_extra_field_info()", "#14 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('eva_entity_extr...', Array)", "#15 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(610): Drupal\\Core\\Extension\\ModuleHandler->invokeAll('entity_extra_fi...')", "#16 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityManager.php(345): Drupal\\Core\\Entity\\EntityFieldManager->getExtraFields('media', 'image')", "#17 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(160): Drupal\\Core\\Entity\\EntityManager->getExtraFields('media', 'image')", "#18 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityDisplayBase.php(143): Drupal\\Core\\Entity\\EntityDisplayBase->init()", "#19 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(175): Drupal\\Core\\Entity\\EntityDisplayBase->__construct(Array, 'entity_view_dis...')", "#20 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(359): Drupal\\Core\\Entity\\Entity\\EntityViewDisplay->__construct(Array, 'entity_view_dis...')", "#21 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(430): Drupal\\Core\\Entity\\EntityStorageBase->mapFromStorageRecords(Array)", "#22 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(405): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->_doCreateFromStorageRecord(Array)", "#23 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(329): Drupal\\Core\\Config\\Entity\\ConfigEntityStorage->createFromStorageRecord(Array)", "#24 /var/www/html/drupal/web/modules/contrib/features/src/FeaturesConfigInstaller.php(106): Drupal\\Core\\Config\\ConfigInstaller->createConfiguration('', Array)", "#25 /var/www/html/drupal/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(132): Drupal\\features\\FeaturesConfigInstaller->createConfiguration('', Array)", "#26 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(268): Drupal\\Core\\Config\\ConfigInstaller->installDefaultConfig('module', 'islandora_demo')", "#27 /var/www/html/drupal/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, true)", "#28 /var/www/html/drupal/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(79): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, true)", "#29 [internal function]: Drush\\Drupal\\Commands\\pm\\PmCommands->enable(Array, Array)", "#30 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)", "#31 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\\AnnotatedCommand\\CommandProcessor->runCommandCallback(Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#32 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\\AnnotatedCommand\\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#33 /var/www/html/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\\AnnotatedCommand\\CommandProcessor->process(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput), Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#34 /var/www/html/drupal/vendor/symfony/console/Command/Command.php(251): Consolidation\\AnnotatedCommand\\AnnotatedCommand->execute(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#35 /var/www/html/drupal/vendor/symfony/console/Application.php(964): Symfony\\Component\\Console\\Command\\Command->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#36 /var/www/html/drupal/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Consolidation\\AnnotatedCommand\\AnnotatedCommand), Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#37 /var/www/html/drupal/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#38 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\\Component\\Console\\Application->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#39 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\\Runtime\\Runtime->doRun(Array)", "#40 /var/www/html/drupal/vendor/drush/drush/drush.php(66): Drush\\Runtime\\Runtime->run(Array)", "#41 /var/www/html/drupal/vendor/drush/drush/drush(4): require('/var/www/html/d...')", "#42 {main}", " [error]  Drush command terminated abnormally due to an unrecoverable error. "], "stdout": "The following module(s) will be enabled: islandora_demo, controlled_access_terms_default_configuration, islandora_image\n\n // Do you want to continue?: yes.                                              \n\nError: Call to a member function getSchema() on null in Drupal\\views\\EntityViewsData->mapFieldDefinition() (line 383 of /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php).", "stdout_lines": ["The following module(s) will be enabled: islandora_demo, controlled_access_terms_default_configuration, islandora_image", "", " // Do you want to continue?: yes.                                              ", "", "Error: Call to a member function getSchema() on null in Drupal\\views\\EntityViewsData->mapFieldDefinition() (line 383 of /var/www/html/drupal/web/core/modules/views/src/EntityViewsData.php)."]}
```

**Comment by dannylamb** [comment]
@Natkeeran Yeah, should be.  After the giant wall of red is there a blue `...ignoring`?

**Comment by Natkeeran** [comment]
Thanks @dannylamb
